parameters:
    database_host: 127.0.0.1
    database_port: 
    database_name: somostin_enfermeria
    database_user: root
    database_password: '123456'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 7294070feb9d7f6793a91a1bc842512c
    database_path: null
